// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-transactions.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-transactions.ts
var list_transactions_default = defineTool({
  name: "list_transactions",
  title: "List transactions",
  description: "List the signed-in user's recent income and expense transactions, newest first.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(20).describe("Maximum number of transactions to return."),
    category: z.string().optional().describe("Optional category filter, e.g. food, bills, income."),
    type: z.enum(["income", "expense"]).optional().describe("Optional transaction type filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, category, type }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("transactions").select("id,name,amount,type,category,payment_method,transaction_date,description").order("transaction_date", { ascending: false }).limit(limit ?? 20);
    if (category) query = query.eq("category", category);
    if (type) query = query.eq("type", type);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { transactions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/add-transaction.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var CATEGORIES = [
  "food",
  "shopping",
  "transport",
  "entertainment",
  "bills",
  "health",
  "recharges",
  "education",
  "travel",
  "income",
  "other"
];
var PAYMENT_METHODS = [
  "upi",
  "debit_card",
  "credit_card",
  "cash",
  "neft",
  "auto_pay",
  "other"
];
var add_transaction_default = defineTool2({
  name: "add_transaction",
  title: "Add transaction",
  description: "Record a new income or expense transaction for the signed-in user.",
  inputSchema: {
    name: z2.string().trim().min(1).describe("Short label, e.g. 'Groceries'."),
    amount: z2.number().positive().describe("Amount in rupees."),
    type: z2.enum(["income", "expense"]).describe("Whether this is income or an expense."),
    category: z2.enum(CATEGORIES).default("other").describe("Transaction category."),
    payment_method: z2.enum(PAYMENT_METHODS).default("upi").describe("Payment method used."),
    transaction_date: z2.string().optional().describe("Date in YYYY-MM-DD format. Defaults to today."),
    description: z2.string().optional().describe("Optional note.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("transactions").insert({
      user_id: ctx.getUserId(),
      name: input.name,
      amount: input.amount,
      type: input.type,
      category: input.category ?? "other",
      payment_method: input.payment_method ?? "upi",
      transaction_date: input.transaction_date ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10),
      description: input.description ?? null
    }).select();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data?.[0] ?? null) }],
      structuredContent: { transaction: data?.[0] ?? null }
    };
  }
});

// src/lib/mcp/tools/list-debts.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_debts_default = defineTool3({
  name: "list_debts",
  title: "List debts",
  description: "List the signed-in user's debts with outstanding amounts, interest rates and EMIs.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("debts").select("id,name,type,outstanding_amount,principal_amount,interest_rate,minimum_payment,next_payment_date").order("interest_rate", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { debts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-investments.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_investments_default = defineTool4({
  name: "list_investments",
  title: "List investments",
  description: "List the signed-in user's investment holdings with invested and current values.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("investments").select("id,name,type,invested_amount,current_value,units,nav,risk_level,purchase_date").order("current_value", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const invested = (data ?? []).reduce((sum, i) => sum + Number(i.invested_amount ?? 0), 0);
    const current = (data ?? []).reduce((sum, i) => sum + Number(i.current_value ?? 0), 0);
    return {
      content: [{ type: "text", text: JSON.stringify({ investments: data ?? [], invested, current }) }],
      structuredContent: {
        investments: data ?? [],
        total_invested: invested,
        total_current_value: current,
        gain: current - invested
      }
    };
  }
});

// src/lib/mcp/tools/list-savings-goals.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_savings_goals_default = defineTool5({
  name: "list_savings_goals",
  title: "List savings goals",
  description: "List the signed-in user's savings goals with progress toward each target.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("savings_goals").select("id,name,category,target_amount,current_amount,target_date,is_completed").order("target_date", { ascending: true });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const goals = (data ?? []).map((g) => ({
      ...g,
      progress_percent: Number(g.target_amount) > 0 ? Math.round(Number(g.current_amount) / Number(g.target_amount) * 100) : 0
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(goals) }],
      structuredContent: { goals }
    };
  }
});

// src/lib/mcp/tools/financial-summary.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var financial_summary_default = defineTool6({
  name: "financial_summary",
  title: "Financial summary",
  description: "Summarize the signed-in user's finances for a period: income, expenses, savings rate, spending by category, total debt and portfolio value.",
  inputSchema: {
    months: z3.number().int().min(1).max(24).default(1).describe("How many recent months to include.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ months }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const since = /* @__PURE__ */ new Date();
    since.setMonth(since.getMonth() - (months ?? 1));
    const sinceDate = since.toISOString().slice(0, 10);
    const [txRes, debtRes, invRes] = await Promise.all([
      supabase.from("transactions").select("amount,type,category,transaction_date").gte("transaction_date", sinceDate),
      supabase.from("debts").select("outstanding_amount,interest_rate,minimum_payment"),
      supabase.from("investments").select("invested_amount,current_value")
    ]);
    const firstError = txRes.error ?? debtRes.error ?? invRes.error;
    if (firstError) return { content: [{ type: "text", text: firstError.message }], isError: true };
    const txs = txRes.data ?? [];
    const income = txs.filter((t) => t.type === "income").reduce((s, t) => s + Number(t.amount), 0);
    const expenses = txs.filter((t) => t.type !== "income").reduce((s, t) => s + Number(t.amount), 0);
    const byCategory = {};
    for (const t of txs) {
      if (t.type === "income") continue;
      byCategory[t.category] = (byCategory[t.category] ?? 0) + Number(t.amount);
    }
    const debts = debtRes.data ?? [];
    const totalDebt = debts.reduce((s, d) => s + Number(d.outstanding_amount ?? 0), 0);
    const monthlyEmi = debts.reduce((s, d) => s + Number(d.minimum_payment ?? 0), 0);
    const avgInterest = debts.length ? debts.reduce((s, d) => s + Number(d.interest_rate ?? 0), 0) / debts.length : 0;
    const investments = invRes.data ?? [];
    const invested = investments.reduce((s, i) => s + Number(i.invested_amount ?? 0), 0);
    const portfolioValue = investments.reduce((s, i) => s + Number(i.current_value ?? 0), 0);
    const summary = {
      period_months: months ?? 1,
      since: sinceDate,
      income,
      expenses,
      net: income - expenses,
      savings_rate_percent: income > 0 ? Math.round((income - expenses) / income * 100) : 0,
      spending_by_category: byCategory,
      total_debt: totalDebt,
      monthly_emi: monthlyEmi,
      average_interest_rate: Number(avgInterest.toFixed(2)),
      total_invested: invested,
      portfolio_value: portfolioValue,
      portfolio_gain: portfolioValue - invested
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "xgwgnxjondblftyamkgu";
var mcp_default = defineMcp({
  name: "money-maestro",
  title: "Money Maestro",
  version: "0.1.0",
  instructions: "Tools for Money Maestro, a personal finance tracker. Use `financial_summary` for an overview of income, expenses, savings rate, debt and portfolio. Use `list_transactions`, `list_debts`, `list_investments` and `list_savings_goals` to inspect details, and `add_transaction` to record new income or expenses. All data belongs to the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    financial_summary_default,
    list_transactions_default,
    add_transaction_default,
    list_debts_default,
    list_investments_default,
    list_savings_goals_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
